spring.application.name=webapp
# Tomcat Server port ??
server.port=8081

# DB ?? ??
spring.datasource.url=jdbc:mysql://localhost:3306/gsm22
spring.datasource.username=root
spring.datasource.password=12345
# JDBC Driver API
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Spring Data JPA API? ??? ?? ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect